import { evaluateReading } from '../midband';
import cases from './server-midband-cases.json';

/**
 * Cross-implementation contract.
 *
 * The phone computes a level so the operator sees it immediately, standing at
 * the tank. The server recomputes the same level on sync and its answer is what
 * gets stored (doc 04 §4). If the two ever disagree, the operator is shown one
 * number while a different one is recorded — and nobody would know which to
 * believe, or that anything was wrong at all.
 *
 * These cases are generated by running sru-field-api/lib/midband.js over a grid
 * of inputs, so they are the server's actual answers rather than a transcription
 * of what it is supposed to say. Regenerate whenever either implementation
 * changes; a diff here means the two have drifted.
 */
type Case = {
  in: { heightMm: number; tapeLengthMm: number; bandulSulfurMm: number; dcsLevelMm: number | null };
  out: { ok: boolean; levelMm?: number; deviationMm?: number | null; code?: string };
};

const fixtures = cases as Case[];

describe('parity with the server implementation', () => {
  it('covers both accepted and rejected inputs', () => {
    // Guards the fixture itself: a grid with no invalid inputs would pass while
    // testing none of the rejection paths. That happened on the first attempt.
    const accepted = fixtures.filter((c) => c.out.ok).length;
    const rejected = fixtures.length - accepted;
    expect(accepted).toBeGreaterThan(100);
    expect(rejected).toBeGreaterThan(100);

    const codes = new Set(fixtures.filter((c) => !c.out.ok).map((c) => c.out.code));
    expect(codes).toContain('BANDUL_OUT_OF_RANGE');
    expect(codes).toContain('TAPE_TOO_LONG');
  });

  it.each(fixtures.map((c, i) => [i, c] as const))(
    'case %i matches the server',
    (_index, testCase) => {
      const result = evaluateReading(testCase.in);

      expect(result.ok).toBe(testCase.out.ok);

      if (result.ok && testCase.out.ok) {
        expect(result.levelMm).toBe(testCase.out.levelMm);
        expect(result.deviationMm).toBe(testCase.out.deviationMm ?? null);
      } else if (!result.ok) {
        expect(result.error.code).toBe(testCase.out.code);
      }
    },
  );
});
